import Link from 'next/link'
import { notFound } from 'next/navigation'
import { Header } from '@/components/Header'
import { Card } from '@/components/Card'
import { RiskBadge } from '@/components/RiskBadge'
import { patients } from '@/lib/data'
import { explanation, phenotype, riskLevel, riskScore } from '@/lib/rules'
import { contentWidthClass } from '@/lib/layout'

export default function PatientDetail({ params }: { params: { id: string } }) {
  const p = patients.find(x => x.id === params.id)
  if (!p) notFound()

  const score = riskScore(p)
  const level = riskLevel(score)
  const reasons = explanation(p)
  const aiSummary = `${p.name} is flagged as ${level.toLowerCase()} risk with a ${phenotype(p).toLowerCase()}. Key drivers include ${reasons.join(', ') || 'no major abnormal signals'}. Recommended clinician workflow: review pain trajectory, confirm red-flag symptoms, assess medication adherence and function, and route to care manager, PT, PCP, or pain specialist as appropriate.`

  return (
    <main>
      <Header />
      <section className={`${contentWidthClass} py-5`}>
        <Link href="/" className="text-sm font-semibold text-sky-800 hover:underline">
          ← Back to dashboard
        </Link>

        <div className="mt-3 flex flex-col justify-between gap-3 md:flex-row md:items-end">
          <div>
            <h1 className="text-2xl font-bold text-slate-950">{p.name}</h1>
            <p className="mt-1 text-sm font-medium text-slate-800">
              {p.pathway} · Last check-in: {p.lastCheckIn}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <RiskBadge level={level} />
            <span className="text-xl font-bold">{score}/100</span>
          </div>
        </div>

        <div className="mt-4 grid gap-3 md:grid-cols-3">
          <Card>
            <div className="text-xs font-semibold text-slate-700">Pain / function</div>
            <div className="mt-1 text-2xl font-bold">{p.painScore}/10</div>
            <p className="text-sm font-medium text-slate-800">BPI interference: {p.bpiInterference}/10</p>
          </Card>
          <Card>
            <div className="text-xs font-semibold text-slate-700">Sleep / HRV</div>
            <div className="mt-1 text-2xl font-bold">{p.sleepEfficiency}%</div>
            <p className="text-sm font-medium text-slate-800">
              HRV: {p.hrv} ms · Deep sleep: {p.deepSleepPct}%
            </p>
          </Card>
          <Card>
            <div className="text-xs font-semibold text-slate-700">Labs</div>
            <div className="mt-1 text-lg font-bold">
              CRP {p.crp} · IL-6 {p.il6}
            </div>
            <p className="text-sm font-medium text-slate-800">
              HbA1c {p.hba1c}% · Vit D {p.vitaminD} ng/mL · ESR {p.esr}
            </p>
          </Card>
        </div>

        <div className="mt-4 grid gap-3 md:grid-cols-2">
          <Card>
            <h2 className="text-base font-bold text-slate-950">Explainable phenotype support</h2>
            <p className="mt-2 rounded-lg border border-sky-200 bg-sky-50 p-3 font-semibold text-sky-950">
              {phenotype(p)}
            </p>
            <ul className="mt-3 space-y-1 text-sm font-medium text-slate-900">
              {reasons.map(r => (
                <li key={r}>• {r}</li>
              ))}
            </ul>
          </Card>
          <Card>
            <h2 className="text-base font-bold text-slate-950">AI care-summary placeholder</h2>
            <p className="mt-2 text-sm font-medium leading-snug text-slate-900">{aiSummary}</p>
            <div className="mt-3 rounded-lg border border-slate-200 bg-slate-50 p-2.5 text-xs font-medium text-slate-700">
              In production, this section can be generated by an LLM using only the structured patient record and
              clinician-reviewed rules output.
            </div>
          </Card>
        </div>

        <Card className="mt-4">
          <h2 className="text-base font-bold text-slate-950">Suggested next workflow</h2>
          <div className="mt-3 grid gap-2 md:grid-cols-4">
            {['Review alert', 'Call patient', 'Confirm red flags', 'Route to clinician'].map((x, i) => (
              <div key={x} className="rounded-lg border border-slate-200 bg-slate-50 p-3">
                <div className="mb-1.5 flex h-6 w-6 items-center justify-center rounded-full bg-sky-900 text-xs font-bold text-white">
                  {i + 1}
                </div>
                <div className="text-sm font-semibold text-slate-900">{x}</div>
              </div>
            ))}
          </div>
        </Card>
      </section>
    </main>
  )
}
